library(readr)
library(lubridate)
library(ggplot2)
library(ggjoy)

osha1 <- read_csv("osha/osha_violation-1.csv")
osha2 <- read_csv("osha/osha_violation-2.csv")
osha3 <- read_csv("osha/osha_violation-3.csv")
osha4 <- read_csv("osha/osha_violation-4.csv")
osha5 <- read_csv("osha/osha_violation-5.csv")
osha6 <- read_csv("osha/osha_violation-6.csv")
osha7 <- read_csv("osha/osha_violation-7.csv")
osha8 <- read_csv("osha/osha_violation-8.csv")
osha9 <- read_csv("osha/osha_violation-9.csv")
osha10 <- read_csv("osha/osha_violation-10.csv")
osha11 <- read_csv("osha/osha_violation-11.csv")
osha12 <- read_csv("osha/osha_violation-12.csv")

osha <- rbind(osha1, osha2, osha3, osha4, osha5, osha6, osha7, osha8, osha9, osha10, osha11, osha12)
rm(osha1)
rm(osha2)
rm(osha3)
rm(osha4)
rm(osha5)
rm(osha6)
rm(osha7)
rm(osha8)
rm(osha9)
rm(osha10)
rm(osha11)
rm(osha12)

viol <- osha
rm(osha)
